id: 3b87f75c9b1344c893833d7dd33b7d46
initial_creation_type: ocr
source_metadata:
  volumes:
    2aebfb39ecb94f788fb47ec15bd72302:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
